version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ChatApp
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    depends_on:
      - postgres
    ports:
      - '5500:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    restart: unless-stopped
  # prisma-studio:
  #   container_name: prisma-studio
  #   image: timothyjmiller/prisma-studio:latest
  #   restart: unless-stopped
  #   env_file:
  #     - ./.env
  #   ports:
  #     - 5555:5555
  nest:
    stdin_open: true
    # target: development
    build:
      context: .
      dockerfile: Dockerfile
    command: yarn start:dev
    env_file:
      - ./.env
    volumes:
      - .:/eivydas/src/app
      - ./eivydas/src/app/node_modules
    depends_on:
      - postgres
    ports:
      - '5000:5000'
    restart: always

volumes:
  postgres-data:
  pgadmin-data:
